import type { Metadata } from "next";
import StoreProvider from "./store-provider";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text-white flex flex-col">
        <div className="bg-gray-900 ">
          <StoreProvider>{children}</StoreProvider>
        </div>
      </body>
    </html>
  );
}
